### ISSUE TITLE
Refresh plot not working

### ISSUE THREAD

**Issue by Rubenknex** [Rubenknex/qtplot#10]

**Comment by danielbouman** [comment]
The button doesn't respond, there is also no error message when pressing the button (using qtplot-console). At startup of qtplot, even before loading data, we get `ERROR: Could not parse resistance value`. This is possibly related.

**Comment by danielbouman** [comment]
A workaround is:
1. Click refresh (nothing happens)
2. (Re)select data for either x,y or data (any data will do)
Now the plot well be updated

**Comment by Rubenknex** [comment]
Fixed, was due to changes in behavior on file loading.
