### ISSUE TITLE
Some 2D datasets fail to plot

### ISSUE THREAD

**Issue by danielbouman** [Rubenknex/qtplot#13]
For some 2D datasets only a 1D component is plotted, When trying to select the y-data, the plot is not updated and the follow error message is shown: `ERROR: You cannot have a y-parameter for a 1-D dataset`.

The problem shows up when the second column has a negative start and end. When only this is changes to a positive start and end, plotting works again.   Attached an example dataset that produces this problem.

[20160808_A23112.zip](https://github.com/Rubenknex/qtplot/files/414902/20160808_A23112.zip)

**Comment by Rubenknex** [comment]
Fixed, was caused by the first value in the data file being negative.

The data file reading will first read the metadata at the top of the file, and then stop reading lines when the actual data starts. The check was if the first character was a number, but '-' obviously didn't pass this.
