### ISSUE TITLE
Non-rectangular datasets

### ISSUE THREAD

**Issue by danielbouman** [Rubenknex/qtplot#16]
For non-rectangular datasets vertical line traces cannot be taken over the entire scan range and horizontal line traces do not work at all. Is it possible to get this working for arbitrarily shaped data sets? Attached an example dataset.

[dev4_952.zip](https://github.com/Rubenknex/qtplot/files/456398/dev4_952.zip)

**Comment by Rubenknex** [comment]
I see what you're trying to do :P. This requires a bit of work since the linetraces are currently just a matrix column/row. I can probably start working on it thursday and else friday.
