### ISSUE TITLE
OpenGL error

### ISSUE THREAD

**Issue by danielbouman** [Rubenknex/qtplot#17]
When opening any dataset I get the following error message: 
`INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate`

**Comment by Rubenknex** [comment]
This log message has level INFO and is thus not a warning/error. I started using the python logging module so now also logging messages from all used libraries are recorded and the log is stored in .qtplot/log.txt.
