### ISSUE TITLE
2D data not fully shown

### ISSUE THREAD

**Issue by danielbouman** [Rubenknex/qtplot#18]
In a 2D dataset the highest horizontal trace is never shown, this happens both with a complete and incomplete (ongoing 2D scan) dataset. See for example the attached dataset. On the y-axis is B-field from 0mT to 360mT, however the upper line is at 350mT.

[dev4_1390.zip](https://github.com/Rubenknex/qtplot/files/479375/dev4_1390.zip)

**Comment by Rubenknex** [comment]
Do you have the latest qtplot version? Because I can see the 360mT trace in the current version (dev16).

**Comment by danielbouman** [comment]
It works with dev16
