### ISSUE TITLE
Operations not working at all

### ISSUE THREAD

**Issue by danielbouman** [Rubenknex/qtplot#20]
In version 0.1.0.dev19 the operations don't work at all. When I load any datafile, select an operation and click 'add', nothing happens.

**Comment by Rubenknex** [comment]
For me it still works, can you send the output of `conda list` and a datafile that doesn't work?

**Comment by danielbouman** [comment]
Attached the `conda list`, `pip list`, the python traceback of the error and a datafile that has the issue. Although so far the issue is there for every datafile I opened.

[error_files.zip](https://github.com/Rubenknex/qtplot/files/663195/error_files.zip)

**Comment by Rubenknex** [comment]
I'll take a look at, in the meantime you can revert using `pip install qtplot==0.1.0.dev18`.
