### ISSUE TITLE
Select a datapoint

### ISSUE THREAD

**Issue by danielbouman** [Rubenknex/qtplot#22]
Ability to select a data point on the line cut and keep it selected to this row number, in the .dat file, when switching between data columns. For example, when doing a 4-terminal voltage bias IV-trace you get 3 columns with data: V_bias, I_measure, V_measure. I plot x=V_bias, data=I_measure, I select datapoint V_bias = 0.5 mV and then switch to x=V_measure. I want to see what value V_measure has for V_bias = 0.5 mV.

**Comment by Rubenknex** [comment]
@dbouman1 
I'm not totally sure what you mean here. Do you mean selecting a single datapoint, and then seeing somewhere the values of the other parameters in the same row?

You can plot the relation with (x=V_bias, y=<blank>, z=V_measure) but I guess that's not what you mean.

**Comment by danielbouman** [comment]
Indeed, that is what I want. 

Plotting V_bias vs V_measure is not really usable for my purposes.
