### ISSUE TITLE
Request for new functionality

### ISSUE THREAD

**Issue by jdwatson5** [Rubenknex/qtplot#8]
One nice feature that spyview has that QT_plot doesn't is the ability to take diagonal linecuts.  This is nice for figuring out cross capacitances between gates, extracting charging energies from Coulomb blockade data, etc.  The especially useful thing in spyview is that it shows the values of the starting and ending coordinates which is what allows you to calculate the slope and extract the interesting quantities.  Anyway, it's not super urgent, but it would be a nice feature.

**Comment by Rubenknex** [comment]
This was something that was actually included in an old version but for some reason the functionality disappeared due to some other changes. The code is still in there so it should be a small effort to restore it.

**Comment by Rubenknex** [comment]
The diagonal linecuts are now included again in the latest commit. Do you mean with the starting and ending coordinates those for the x and y-axis? Currently I show on the x-axis of the linecut sqrt((x-x0)^2+(y-y0)^2) which is the 'distance' along the linecut.
